Cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: %w(black white gray),
    message: "%{value} is not a valid color."}
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex."}

  has_many :cat_rental_requests, dependent: :destroy

  def age
    time_ago_in_words(birth_date)
  end

end

Cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING),
    message: "%{value} is not a valid status."}
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    CatRentalRequest.select("*")
      .where("end_date >= ? AND id != ? AND cat_id = ?", start_date, id, cat_id)
      .where("end_date <= ? OR start_date <= ?", end_date, end_date)
  end

  def overlapping_approved_requests
    overlapping_requests
      .select('*')
      .where(status: 'APPROVED')
  end

  def overlapping_pending_requests
    overlapping_requests
      .select('*')
      .where(status: 'PENDING')
  end

  def approve!
    pending = overlapping_pending_requests
    CatRentalRequest.transaction do
      pending.update(status: 'DENIED')
      self.status = 'APPROVED'
      self.save
    end
  end

  def deny!
    self.status = 'DENIED'
    self.save
  end


  private

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors[:base] << 'Approved overlapping rentals exist'
    end
  end

end

Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

Cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @requests = CatRentalRequest.all
    render :index
  end

  def show
    @request = CatRentalRequest.find(params[:id])
    render :show
  end

  def new
    @cats = Cat.all
    render :new
  end

  def create
    @request = CatRentalRequest.new(cat_rental_request_params)

    if @request.save
      redirect_to cat_rental_request_url(@request)
    else
      render :new
    end
  end

  def update
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  def destroy
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

end

Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    render :index
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
  end

end

Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

Cats/app/helpers/cats_helper.rb
module CatsHelper
end

Cats/app/views/cat_rental_requests/index.html.erb
<h2>All the Requests!</h2>

<table>
  <tr>
    <% @requests.first.attributes.each do |k,v| %>
      <td><%= k %></td>
    <% end %>
  </tr>
  <% @requests.each do |request| %>
  <tr>
    <% request.attributes.each do |k,v| %>
    <td><%= v %></td>
    <% end %>
  </tr>
  <% end %>
</table>

Cats/app/views/cat_rental_requests/new.html.erb
<h2>Rent a Cat!</h2>


<form action= '<%= cat_rental_requests_url %>' method='POST'>

  <label for='cats'>Which cat would you like to rent?</label>

  <select name='cat_rental_request[cat_id]'>
    <option value='' disabled selected >--Select cat!</option>
    <% @cats.each do |cat| %>
      <option value= <%= cat.id %> > <%= cat.name %> </option>
    <% end %>
  </select>
  <br>

  <label for='start_date'>Start Date</label>
  <input id='start_date' type='date' name='cat_rental_request[start_date]'>
  <br>

  <label for='end_date'>End Date</label>
  <input id='end_date' type='date' name='cat_rental_request[end_date]'>
  <br>

  <input type='submit' value='Submit request!'>

</form>

Cats/app/views/cat_rental_requests/show.html.erb
<h2> Show me the cat</h2>

<table>
  <tr>
    <% @request.attributes.each do |k,v| %>
      <td><%= k %></td>
    <% end %>
  </tr>
  <tr>
    <% @request.attributes.each do |k,v| %>
    <td><%= v %></td>
    <% end %>
  </tr>

</table>

Cats/app/views/cats/_cat.html.erb
<tr>
  <td><%= cat.name %></td>
  <td><%= link_to "details", (cat_url(cat)) %>
</tr>

Cats/app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>


<form action='<%= action_url %>' method='post'>
  <% if cat.persisted? %>
    <input type='hidden' name='_method' value='PATCH'>
  <% end %>

  <label for='name'>Name</label>
  <input id='name'
    type='text'
    name='cat[name]'
    value= <%= cat.name %> >
  <br>

  <label for='color'>Color</label>
  <select name='cat[color]'>

    <option value=''
      disabled <%= 'selected' if cat.color.nil? %> >
      --Select Color--
    </option>

    <% %w(black white grey).each do |col| %>

      <option value = '<%= col %>'
        <%= 'selected' if cat.color == col %> >
          <%= col.capitalize %></option>

    <% end %>
  </select>
  <br>

  <label for='sex'>Sex</label>
  M<input type='radio' name='cat[sex]' value='M' <%= 'checked' if cat.sex == 'M' || cat.sex.nil? %> >
  F<input type='radio' name='cat[sex]' value='F' <%= 'checked' if cat.sex == 'F' %> >
  <br>

  <label>Description
    <textarea name='cat[description]'><%= cat.description %></textarea>
  </label>
  <br>

  <label for='birth_date'>Birth Date</label>
  <input id='birth_date' type = 'date'        name='cat[birth_date]' value = <%= cat.birth_date ? cat.birth_date : "" %> >
  <br>

  <input type='submit' value='Add cat!'>
</form>

Cats/app/views/cats/edit.html.erb
<h2>Update a cat!</h2>

<%= render 'form', cat: @cat %>

Cats/app/views/cats/index.html.erb
<h2>All the Cats!</h2>

<table width = 200>
<%= render @cats %>
</table>

Cats/app/views/cats/new.html.erb
<h2>Make a new cat!</h2>

<%= render 'form', cat: @cat %>

Cats/app/views/cats/show.html.erb
<h2> <%= @cat.name %> </h2>

<ul>
<% @cat.attributes.each do |k, v| %>
  <% next if k == "created_at" || k == "updated_at" || v.nil? %>
  <li><%= "#{k}: #{v}" %></li>
<% end %>
</ul>

<% requests = @cat.cat_rental_requests.order(:start_date) %>
<% unless requests.empty? %>
<table>
  <tr>
    <% requests.first.attributes.each do |k, v| %>
      <td> <%= k %> </td>
    <% end %>
  </tr>
  <% requests.each do |request| %>
    <tr>
      <% request.attributes.each do |k, v| %>
        <td> <%= v %> </td>
      <% end %>
      <% if request.status == 'PENDING' %>
        <td> <%= button_to 'Approve!', cat_rental_request_url(request), method: 'patch' %> </td>
        <td> <%= button_to 'Denied!', cat_rental_request_url(request), method: 'delete' %> </td>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>

Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>